# Generated by Django 2.0.5 on 2019-08-22 15:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
