# Generated by Django 2.0.5 on 2019-08-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='body',
            new_name='content',
        ),
    ]
